apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-2umr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-2umr
    app.kubernetes.io/part-of: test-app-pcsb
  name: devfile-sample-python-basic-2umr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-2umr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-2umr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-umlv-tenant/test-app-pcsb/devfile-sample-python-basic-2umr@sha256:c8ac4a7a1cb85b6a2ca86afa460993428b38fdd42cdf37b3920e2a414b7c9e09
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
